@startuml

Node <|-- CharacterBody2D
Node <|-- StateNode
Node <|-- StateMachineNode
CharacterBody2D <|-- player
StateNode <|-- walk_state
StateNode <|-- idle_state

class StateMachineNode {
  StateNode initial_node_state
  Dictionary node_states
  function _ready
  function transition_to
}
note left of StateMachineNode::_ready
 在此注册StateNode到所有的子节点中，
 每个子节点都连接transition_to
end note
note left of StateMachineNode::initial_node_state
 默认状态
end note
' note "This is a floating note" as N1

' class Foo
' note left: On last defined class

@enduml